from directive_match import *
#
# print(pattern_match('/$', '/anything'))

patterns = ["*-bed-flats-*","*-bed-houses*","*-bed-proper*","*/studio/*","/content/*","*-bed-*","*/agents/*/contact/**","*/agents/branch/*/properties/*","*/agents/contact/*","*/agents/search/*","*/apartment/*","*/flat/*","*/sales-agents*","*/studio-*","*max-bedrooms=","*new-home-flag=T","*radius=","/agents/website-redirect/*","/banners/alert-website-redirect/*","/banners/local-agent-website-redirect/*","/banners/mortgage-link-redirect/*","/my-account/*","/overseas/*-bed-*","/pattern-library/","/properties/*/epc-*","/properties/*/floor-plan-*","/properties/*/image-*","/properties/*/img_","/student/*-bed-flats-*","/student/*-bed-houses*"]
urls = ["/","/for-sale/","/for-sale/property/london/","/for-sale/property/london/?page=1","/for-sale/commercial/","/for-sale/flats/london/","/for-sale/apartments/london/","/for-sale/property/barking/?radius=2.0","/for-sale/flats-apartments/bath/?new-home-flag=T","/for-sale/flats-apartments/bath/?max-bedrooms=3","/for-sale/flats-apartments/bath/?max-price=90000&min-price=50000","/property/england/","/property/adderbury/","/property/oxfordshire/","/property/ox10/","/to-rent/","/to-rent/property/london/","/to-rent/property/london/?page=1","/to-rent/property/london/?view=map","/to-rent/property/london/?view=grid","/to-rent/commercial/","/property-valuation/","/price-guide/","/instant-valuation/","/instant-valuation/?postcode=SW1V%203RA&type=for-sale","/new-homes/","/new-homes/developers/","/agents/","/agents/xxxxxx/xxxx/contact/12657710/?form-name=details-contact","/agents/contact/12657710/?form-name=details-contact","/agents/website-redirect/?redirect-token=iNaHMlACQ%2FM13m8cazfYObsHfHkK5Loo0WUoWaF9Ojkx9t%2Bj6VQoqmqQxkWW5%2B5V","/agents/newbury/?agent-name=Savills&agent-search-type=branches&company-url-name=savills","/agents/branch/savills-newbury/properties/?search-type=for-sale&under-offer=true&view=grid","/uk-house-prices/","/content/","/content/tag/advice/","/content/experts-make-their-property-market-predictions-for-2020/","/content/tag/mortgages/","/student/","/student/4-bed-houses/oxford/","/farms-land/","/overseas/","/my-account/","/details/12657568/","/details/12645812/?channel=student","/pattern-library/","/for-sale/2-bed-flats-apartments/bath/","/to-rent/2-bed-flats-apartments/bath/","/to-rent/2-bed-houses/bath/","/for-sale/2-bed-houses/bath/","/for-sale/2-bed-property/bath/","/to-rent/2-bed-property/bath/","/for-sale/studio/bath/","/studio/2-bed-property/bath/","/content/","/content/onthemarket-survey-highlights-increasing-interest-in-energy-efficient-homes/","/agents/search/?agent-name=Pygott+%26+Crone&agent-search-type=branches","/for-sale/apartment/bath/","/to-rent/apartment/bath/","/to-rent/flat/bath/","/for-sale/flat/bath/","/agents/website-redirect/?redirect-token=tgASxOh7KvtuIJB3AC3nkdBrMEXVu0epeHTN6sdvwuI9rvvfrBMuyRlwUjIUR1%2F6","/my-place/my-account/","/my-place/","/overseas/2-bed-property/bahamas/","/overseas/2-bed-houses/bahamas/","/student/2-bed-flats-apartments/bath/","/student/2-bed-houses/bath/"]
for pattern in patterns:
    print(pattern)
    for url in urls:
        if pattern_match(pattern, url):
            print(url)
    print('\n')